service: products-list
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript

functions:
  getProductsList:
    handler: index.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: index.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true

