openapi: 3.1.3
info:
  title: Product list service - OpenAPI 3.0
  description: |-
    Product list service
  version: 1.0.0
servers:
  - url: https://j9qub2jznd.execute-api.us-east-1.amazonaws.com/dev/
paths:
  /products:
    get:
      summary: Get all products products
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{product_id}:
    get:
      summary: Get product by ID
      description: Returns a single product
      operationId: getPetById
      parameters:
        - name: product_id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
      security:
        - api_key: []
        - petstore_auth:
            - write:pets
            - read:pets
components:
  schemas:
    Product:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        count:
          type: integer
          format: int64
          example: 1
        description:
          type: string
          example: Some description
        title:
          type: string
          example: Crane
        price:
          type: number
          format: float
          example: 9.99
        image:
          type: string
          description: Image url
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header